### ISSUE TITLE
bwa-mem2 index support

### ISSUE THREAD

**Issue by gudeqing** [ETCHING-team/ETCHING#4]
Hi, I am testing the latest version ETCHING, but got the following error in the log file:

ERROR!!! /etching/bin/etching_filter line 206: We cannot find /home/hxbio04/dbs/hg19/hs37d5.fa.bwt.

Below is my reference fasta index list, in which indexing files were generated by bwa-mem2. The exact expected file does not exist, so does this mean that bwa-mem2 is not supported currently?

![image](https://github.com/ETCHING-team/ETCHING/assets/30919159/53c11875-4206-4b1a-a9dc-7165b4a8437c)

**Comment by Dohun-Yi** [comment]
Thank you for using ETCHING and reporting this issue.
At the moment, we regret to inform you that we do not provide official support for bwa-mem2.

Nonetheless, bwa-mem2 shares parameters with bwa-mem, which means you can make slight adjustments to the "etching_filter" code and command to use bwa-mem2.

Here's what you can do:
* Remove lines 196-211 from "etching_filter." These lines are responsible for checking the existence of the bwa-mem index.
* When running the ETCHING command, add "-B /your/path/to/bwa-mem2".

We have conducted testing with bwa-mem2 using the tiny_demo data, and we observed that it produces identical results to bwa-mem.

Please exercise caution, as bwa-mem2 hasn't undergone comprehensive testing. If you decide to use it, please be aware of the potential risks.

We will be adding support for bwa-mem2 in the near future.

Thanks.

**Comment by gudeqing** [comment]
@Dohun-Yi Thank you for your detail response.  My solution:  build bwa-mem index independently , and put all index files together with the ones generated by bwa-mem2, thus bwa-mem and bwa-mem2 index file are both available for any tools in my pipelines.
![image](https://github.com/ETCHING-team/ETCHING/assets/30919159/e2b12247-6fcf-498c-af8a-738f4b321e2e)
